source 'https://rubygems.org'

# Bundle edge Rails instead:
gem 'rails'
gem 'inherited_resources'
gem 'sqlite3'

#gem 'ruby-debug-ide', '0.4.16'
#gem 'mysql2'
#gem 'ace'

#Pour utiliser has_secure_password
gem 'bcrypt-ruby', :require => "bcrypt"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'ejs'
  gem 'uglifier'
  gem 'coffee-rails'
  gem 'jquery-rails'
  gem 'backbone-rails'
end


