source 'https://rubygems.org'

# Bundle edge Rails instead:
gem 'rails'

gem 'sqlite3'

#gem 'ruby-debug-ide', '0.4.16'
#gem 'mysql2'
#gem 'ace'

#Pour utiliser has_secure_password
gem 'bcrypt-ruby', :require => "bcrypt"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'backbone-rails'